### ISSUE TITLE
HW 7

### ISSUE THREAD

**Issue by john45** [alex-rns/RoR_blog#1]
GOOD JOB, there are some notices:
* you can skip this validation in posts, relationship check automatically
```ruby
  validates :author_id, presence: true
```
* you shouldn't allow the user to this page until hi is authorized
`https://hw7-blog.herokuapp.com/posts/new`

**Comment by alex-rns** [comment]
Thanks for the notices!
 **Fixed.**
https://github.com/alex-rns/RoR_blog/commit/1732085337f8b5180eb0ffb5c44844b21cedf42d
