### ISSUE TITLE
HW 10

### ISSUE THREAD

**Issue by john45** [alex-rns/RoR_blog#2]
## Good job
There are some improvements:
- in app/controllers/votes_controller.rb
```ruby
render 'votes/vote'
```
you can write just
```ruby
render 'vote'
```
- you can avoid set_post and get a post through a comment - @comment.post
- remove useless method:   def votes_params
- in app/controllers/sessions_controller.rb use, because your variant works but it's depricated 
```ruby
Author.find_by(email: params[:email])
instead
Author.find_by_email(params[:email])
```
- instead, code below, use scopes and global settings for pagination
```ruby
    @posts = Post.all.order(updated_at: :desc, created_at: :desc).paginate(page: params[:page], per_page: 8)
```
- in app/controllers/comments_controller.rb you can also skip retrieving post and get it from comment

**Comment by alex-rns** [comment]
Thanks for a suggested improvements!
Code fixed.
